run_name: resnet18_cosine
seed: 42

data:
  data_dir: ./datasets
  batch_size: 128
  num_workers: 2
  data_aug: true

model:
  name: resnet18

train:
  epochs: 100
  output_dir: ./outputs

optimizer:
  name: sgd
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  name: cosine
  t_max: 100